services:

  db:
    container_name: DB_el_psy_congroo
    image: postgres:latest
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    networks:
      - dbnet

networks:
  dbnet:
    driver: bridge

volumes:
  pgdata: